# NOTE: I know this is hard-coded, but I really like how it looks
font = "Iosevka Rounded:size=16"
terminal = "{{ general.terminal }} -e"
prompt = ": "

width = 60
horizontal-pad = 32
vertical-pad = 16
inner-pad = 16
line-height = 24
tabs = 4

[colors]
background = "{{ colors.background | replace('#', '') }}aa"
text = "{{ colors.foreground | replace('#', '') }}ff"
selection-text = "{{ colors.foreground | replace('#', '') }}ff"
border = "{{ colors.bright.black | replace('#', '') }}aa"
selection-match = "{{ colors.bright.blue | replace('#', '') }}ff"
match = "{{ colors.bright.blue | replace('#', '') }}ff"
selection = "{{ colors.normal.white | replace('#', '') }}aa"

[border]
radius = 10
width = 2

[key-bindings]
next = "Control+j"
prev = "Control+k"
delete-line-forward = "none"
