music_directory "~/Music"

pid_file "~/.config/mpd/pid"
db_file "~/.config/mpd/db"
state_file "~/.config/mpd/state"

bind_to_address "localhost"
port "6600"

audio_output {
    type "alsa"
    name "Main alsa output"
    format "192000:24:*"
}

auto_update "yes"
restore_paused "yes"
