require("indent_blankline").setup {
    char = "▏",
    context_char = "▏",
    show_current_context = true,
    show_current_context_start = false,
    show_first_indent_level = true,
    context_highlight_list = { "Warning" },
    context_patterns = {
        -- Defaults
        "class",
        "^func",
        "method",
        "^if",
        "while",
        "for",
        "with",
        "try",
        "except",
        "arguments",
        "argument_list",
        "object",
        "dictionary",
        "element",
        "table",
        "tuple",
        "do_block",
        "Block",
        "InitList",
        "FnCallArguments",
        "IfStatement",
        "ContainerDecl",
        "SwitchExpr",
        "IfExpr",
        "ParamDeclList",

        -- Rust
        "struct",
        "impl",
        "enum",
        "match",
        "loop",
        "mod",
        "macro",
        "let",
        "block",
    },
    show_trailing_blankline_indent = false,
    max_indent_increase = 1,
    viewport_buffer = 1000,
    use_treesitter = false,
}
