if vim.g.started_by_firenvim then -- If loaded by Firenvim (https://github.com/glacambre/firenvim)
  require "user.colorscheme"
  require "user.keymaps"
  require "user.firenvim"
else
  require "user.options"
  require "user.keymaps"
  require "user.plugins"
  require "user.colorscheme"
  require "user.cmp"
  require "user.lsp"
  require "user.telescope"
  require "user.treesitter"
  require "user.autopairs"
  require "user.comment"
  require "user.gitsigns"
  require "user.nvim-tree"
  require "user.bufferline"
  require "user.lualine"
  require "user.toggleterm"
  require "user.project"
  require "user.impatient"
  require "user.indentline"
  require "user.alpha"
  require "user.whichkey"
  require "user.autocommands"
end
